### ISSUE TITLE
map() got an unexpected keyword argument 'arrow_schema'

### ISSUE THREAD

**Issue by masapasa** [richarddwang/hugdatafast#1]
cola_val = tokenized_cola['validation']
lm_dataset = LMTransform(cola_val, max_len=20, text_col='text_idxs').map()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-5cb0bbad1867> in <module>
      1 cola_val = tokenized_cola['validation']
----> 2 lm_dataset = LMTransform(cola_val, max_len=20, text_col='text_idxs').map()
      3 
      4 print('Original dataset:')
      5 print('num of samples:', len(cola['validation']))

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/hugdatafast/transform.py in map(self, split_kwargs, cache_dir, cache_name, **kwargs)
     56       kwargs.update(split_kwargs[split])
     57       if hasattr(kwargs, 'remove_columns'): self._check_outcols(kwargs['remove_columns'], split)
---> 58       new_dsets[split] = self._map(dset, split, **kwargs)
     59     # return
     60     if self.single: return new_dsets['Single']

~/anaconda3/envs/fastai2/lib/python3.7/site-packages/hugdatafast/transform.py in _map(self, hf_dset, split, batch_size, **kwargs)
    215     output_schema = self.get_output_schema(hf_dset, kwargs.pop('test_batch_size', 20))
    216     return hf_dset.map(function=self, batched=True, batch_size=batch_size, with_indices=True,
--> 217                             arrow_schema=output_schema, **kwargs)
    218 
    219   def get_output_schema(self, hf_dset, test_batch_size=20):

TypeError: map() got an unexpected keyword argument 'arrow_schema'

**Comment by richarddwang** [comment]
Hi, Thanks for the report !
This is due to the update of huggingface/nlp.
I have push some fixes and created a new version of pypi.
It should work now. If it is not, please reopen the issue.
