### ISSUE TITLE
doesn't install fastai latest version

### ISSUE THREAD

**Issue by deep-diver** [richarddwang/hugdatafast#3]
the doc says
> This will install also the lastest fastai and nlp.

however, when I have tested to use `hugdatafast`, I have ended up install fastai myself via `pip install fastai --upgrade`. 

the following import statement
`from hugdatafast import *`

it complained below
```
ModuleNotFoundError: No module named 'fastai.text.all'
```

**Comment by deep-diver** [comment]
I was using the Colab environment by the way

**Comment by richarddwang** [comment]
Hi, this is because Colab has pre installed an old fastai (v1).
I've made the latest hugdatafast requiring fastai 2.0.8

Pip install hugdatafast and follow Colab's instruction to restart the runtime.
Thanks for the report. Happy coding !
